name: Compile Realtime

on: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'
      - 'staging-release'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: cd Common && npm install
      - run: cd CommonServer && npm install
      - run: cd Realtime && npm install && npm run compile
  