name: Licensing Docker Build

on: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'
      - 'staging-release'
  pull_request:
  
jobs:
 # define job to build docker image
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      # build image for licensing
      - name: build docker image
        run: npm run build-ci licensing